version: '3.9'

services:
  shop_api:
    container_name: shop_api
    build:
      context: .
    command: >
      sh -c "python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    ports:
      - "${SHOP_API_PORT}:8000"
    env_file:
      - .env
    depends_on:
      - shop_api_db
      - redis
    networks:
      - shop_net

  shop_api_db:
    container_name: shop_api_db
    image: postgres:14
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - shop_api-data:/var/lib/postgresql/data
    networks:
      - shop_net

  redis:
    container_name: redis
    image: redis:7
    networks:
      - shop_net

volumes:
  shop_api-data:

networks:
  shop_net:
